//
// Created by francisco on 31/03/18.
//

#ifndef MY_LIB_ARITHMETICCOMPRESSORDATAGENERATOR_H
#define MY_LIB_ARITHMETICCOMPRESSORDATAGENERATOR_H



#endif //MY_LIB_ARITHMETICCOMPRESSORDATAGENERATOR_H
